### ISSUE TITLE
Support loadBalancerIP for qBittorrent Torrent Service

### ISSUE THREAD

**Issue by alexmorbo** [M0NsTeRRR/helm-charts#156]
**What would you like to be added**:
Currently, the qBittorrent torrent service in the Helm chart is configured as follows:
```
torrent:
  type: ClusterIP
  port: 8388
  annotations: {}
```

However, it lacks support for specifying a loadBalancerIP when type: LoadBalancer is used. 
This feature is essential for users who need to assign a static external IP address for the service.

**What is being requested:**
Add support for the loadBalancerIP parameter to the torrent service configuration in the Helm chart.

**Why is this needed**:
Static IP Configuration: I reserve ip address in MetalLB and forwarding port to this IP address from my router.

**Proposed Solution:**
Extend the `torrent` service configuration in the Helm chart to include an optional loadBalancerIP field. 
The updated configuration might look like this:

```
torrent:
  type: LoadBalancer
  port: 8388
  loadBalancerIP: 192.168.1.100
  annotations: {}
```

**Additional Context:**
- This change would not affect users who use the default ClusterIP or other configurations.
- Updating the chart documentation to include examples of using loadBalancerIP would also be beneficial.

--

Thank you for considering this feature request!
