### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by djjudas21** [M0NsTeRRR/helm-charts#192]
**What happened**:

I'm new to qbittorrent in containers. I have configured my qbittorrent deployment with the gluetun sidecar, configured for SurfShark. The containers start up fine but the service for the UI on port 80 times out. I figure it's something to do with the VPN routing.

I have tried both with and without the squat plugin. I tried changing the service port to 8080, as that's what the container listens on.

**What you expected to happen**:

I should be able to access the qbittorrent UI.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
# values.yaml
qbittorrent:
  replicaCount: 1

  image:
    registry: ghcr.io
    repository: home-operations/qbittorrent
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""
    sha: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  # -- Deployment strategy
  strategy:
    type: Recreate

  # -- Environment variables to add to the qbittorrent pods
  extraEnv: []
  # -- Environment variables from secrets or configmaps to add to the qbittorrent pods
  extraEnvFrom: []

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Automatically mount a ServiceAccount's API credentials?
    automount: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # -- If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    privileged: false
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  service:
    web:
      type: ClusterIP
      port: 8080
      # -- Annotations to add to the web service
      annotations: {}
    torrent:
      type: ClusterIP
      port: 8388
      # -- Annotations to add to the torrent service
      annotations: {}

  # -- Creating PVC to store configuration
  config:
    persistence:
      enabled: true
      # -- Size of persistent disk
      size: 5Gi
      # -- Annotations for PVCs
      annotations: {}
      # -- Access modes of persistent disk
      accessModes:
        - ReadWriteOnce
      # -- Config name
      name: ""
      # -- Name of the permanent volume to reference in the claim.
      # Can be used to bind to existing volumes.
      volumeName: ""

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: qb.gazeley.uk
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: qbittorrent-tls
        hosts:
          - qb.gazeley.uk

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # -- Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # -- Gluetun sidecar
  gluetun:
    enabled: true
    extraEnv:
    - name: VPN_SERVICE_PROVIDER
      value: surfshark
    - name: OPENVPN_USER
      value: *******
    - name: OPENVPN_PASSWORD
      value: *******
    - name: SERVER_COUNTRIES
      value: "United Kingdom"
    resources:
      limits:
        squat.ai/tun: 0

  # -- Prometheus-qbittorrent-exporter sidecar
  prometheusQbittorrentExporter:
    enabled: false
    image:
      registry: ghcr.io
      repository: esanchezm/prometheus-qbittorrent-exporter
      pullPolicy: IfNotPresent
      tag: "v1.6.0"
      sha: ""
    extraEnv: []
    extraEnvFrom: []
    volumeMounts: []
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

    serviceMonitor:
      # -- If true, a ServiceMonitor CRD is created for a prometheus operator
      enabled: false
      path: /metrics
      # -- If set create the `ServiceMonitor` in an alternate namespace.
      namespace:
      labels: {}
      interval: 30s
      scheme: http
      tlsConfig: {}
      scrapeTimeout: 30s
      relabelings: []
      metricRelabelings: []
      targetLabels: []
      service:
        # -- Metrics service port to scrape
        port: 8100

  # -- Extra containers to add to qbittorrent deployment
  extraContainers: []

# -- Generic device plugin
# -- https://github.com/squat/generic-device-plugin
# -- A Kubernetes device plugin to schedule generic Linux devices (used for /dev/tun)
genericDevicePlugin:
  # -- Enable generic device plugin daemonset
  enabled: false

  image:
    registry: ghcr.io
    repository: squat/generic-device-plugin
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "36bfc606bba2064de6ede0ff2764cbb52edff70d"
    sha: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  # -- Deployment strategy
  updateStrategy:
    type: RollingUpdate

  # -- Environment variables to add to the qbittorrent pods
  extraEnv: []
  # -- Environment variables from secrets or configmaps to add to the qbittorrent pods
  extraEnvFrom: []

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Automatically mount a ServiceAccount's API credentials?
    automount: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # -- If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext:
    privileged: true

  priorityClassName: system-node-critical

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  serviceMonitor:
    # -- If true, a ServiceMonitor CRD is created for a prometheus operator
    enabled: false
    path: /metrics
    # -- If set create the `ServiceMonitor` in an alternate namespace.
    namespace:
    labels: {}
    interval: 30s
    scheme: http
    tlsConfig: {}
    scrapeTimeout: 30s
    relabelings: []
    metricRelabelings: []
    targetLabels: []
    service:
      # -- Metrics service port to scrape
      port: 8080
```
```
Defaulted container "qbittorrent" out of: qbittorrent, gluten
QFile::at: Cannot set file position 0
(N) 2025-04-26T20:26:40 - qBittorrent v5.0.4 started. Process ID: 7
(N) 2025-04-26T20:26:40 - Using config directory: /config/qBittorrent
WebUI will be started shortly after internal preparations. Please wait...
(N) 2025-04-26T20:26:40 - Trying to listen on the following list of IP addresses: "0.0.0.0:50413,[::]:50413"
(I) 2025-04-26T20:26:40 - Peer ID: "-qB5040-"
(I) 2025-04-26T20:26:40 - HTTP User-Agent: "qBittorrent/5.0.4"
(I) 2025-04-26T20:26:40 - Distributed Hash Table (DHT) support: ON
(I) 2025-04-26T20:26:40 - Local Peer Discovery support: ON
(I) 2025-04-26T20:26:40 - Peer Exchange (PeX) support: ON
(I) 2025-04-26T20:26:40 - Anonymous mode: OFF
(I) 2025-04-26T20:26:40 - Encryption support: ON
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "127.0.0.1". Port: "TCP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "127.0.0.1". Port: "UTP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "10.42.4.213". Port: "TCP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "10.42.4.213". Port: "UTP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "::1". Port: "TCP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "::1". Port: "UTP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "fe80::c15:8eff:fe13:fd52%eth0". Port: "TCP/50413"
(I) 2025-04-26T20:26:40 - Successfully listening on IP. IP: "fe80::c15:8eff:fe13:fd52%eth0". Port: "UTP/50413"
(W) 2025-04-26T20:26:40 - Couldn't load IP geolocation database. Reason: No such file or directory
(N) 2025-04-26T20:26:40 - Using built-in WebUI.
(N) 2025-04-26T20:26:40 - WebUI translation for selected locale (en) has been successfully loaded.
(N) 2025-04-26T20:26:40 - WebUI: Now listening on IP: *, port: 8080

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080
The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: pGSGSuvtj
You should set your own password in program preferences.
(I) 2025-04-26T20:26:40 - Detected external IP. IP: "x.x.x.x"
(I) 2025-04-26T20:26:40 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Apr 1 01:21:37 2025.
(I) 2025-04-26T20:26:40 - Successfully updated IP geolocation database.
(I) 2025-04-26T20:26:44 - Successfully listening on IP. IP: "fe80::3ee7:6cbc:8659:4212%tun0". Port: "TCP/50413"
(I) 2025-04-26T20:26:44 - Successfully listening on IP. IP: "fe80::3ee7:6cbc:8659:4212%tun0". Port: "UTP/50413"
(I) 2025-04-26T20:26:44 - Successfully listening on IP. IP: "10.8.8.7". Port: "TCP/50413"
(I) 2025-04-26T20:26:44 - Successfully listening on IP. IP: "10.8.8.7". Port: "UTP/50413"
```

**Anything else we need to know?**:

**Environment and application version**:

RKE2 v1.31
